project_id = "myqgnnqltemfpzdxwybj"

[functions.create-anonymous-checkout]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.manage-subscription]
verify_jwt = true

[functions.upscale-image]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = false

[functions.freepik-upscale]
verify_jwt = true

[functions.generate-storyboard-scenes]
verify_jwt = true

[functions.concatenate-videos]
verify_jwt = true
